# Configuracion para el acceso a la Base de Datos
spring.jpa.hibernate.ddl-auto=validate

# Puerto por donde escucha el servidor cuando se inicie
server.port=5000

# Path de la web API
spring.data.rest.base-path=/api

#Lengua local del proyecto
spring.web.locale=es_ES
spring.web.locale-resolver=fixed

#Version de la API
spring.application.version=1.0.0

# Datos de conexion con la base de datos MariaDB
# spring.datasource.url=jdbc:mariadb://database-1.cmpg7ctxwnvf.us-east-1.rds.amazonaws.com:3306/bbddaws?useSSL=true&requireSSL=true

spring.datasource.url=jdbc:mariadb://100.56.55.237:3306/gamerate
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=joseA
spring.datasource.password=110201

spring.jooq.sql-dialect=mariadb

# Muestra las query SQL que ejecuta Hibernate
spring.jpa.show-sql=true

# Habilitar Flyway
spring.flyway.enabled=true
# Ejecutar flyway.repair() automaticamente antes de migrar (opcional)
spring.flyway.repair-on-migrate=true
# Ubicacion de los scripts de migracion
spring.flyway.locations=classpath:db/migration

#Oculta el schema de swagger (los tipos de datos)
springdoc.swagger-ui.default-models-expand-depth=-1

# Configuración JWT (GameRate)
jwt.secret=VnVlc3RyYUNsYXZlU2VjcmV0YVBhcmFHYW1lUmF0ZTIwMjZCYXNlNjRVbHRyYVNlZ3VyYUV4dHJhTG9uZ2VydmFsdWU=
jwt.expiration=86400