# Configuracion para el acceso a la Base de Datos
spring.jpa.hibernate.ddl-auto=validate

# Puerto por donde escucha el servidor cuando se inicie
server.port=8080

server.address=0.0.0.0

# Path de la web API
spring.data.rest.base-path=/api

#Lengua local del proyecto
spring.web.locale=es_ES
spring.web.locale-resolver=fixed

#Version de la API
spring.application.version=1.0.0

# Datos de conexion con la base de datos MariaDB
spring.datasource.url=jdbc:mariadb://localhost:3306/gamerate
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=12345

spring.jooq.sql-dialect=mariadb

# Muestra las query SQL que ejecuta Hibernate
spring.jpa.show-sql=true

# Habilitar Flyway
spring.flyway.enabled=true
# Ejecutar flyway.repair() automaticamente antes de migrar (opcional)
spring.flyway.repair-on-migrate=true
# Ubicacion de los scripts de migracion
spring.flyway.locations=classpath:db/migration

#Oculta el schema de swagger (los tipos de datos)
springdoc.swagger-ui.default-models-expand-depth=-1

# --- CONFIGURACION DE SEGURIDAD JWT ---
jwt.secret=EstaEsUnaClaveSecretaUltraLargaYSuperSeguraParaElProyectoDeGamerateDelTfg2026!
jwt.expiration=86400